
BRONZE_PATHS:
  CHARGES_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/BRONZE/Charges_use.csv
  DAMAGES_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/BRONZE/Damages_use.csv
  ENDORSE_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/BRONZE/Endorse_use.csv
  PRIMARY_PERSON_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/BRONZE/Primary_person_use.csv
  RESTRICT_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/BRONZE/Restrict_use.csv
  UNITS_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/BRONZE/Units_use.csv
SILVER_PATHS:
  CHARGES_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/SILVER/CHARGES/
  DAMAGES_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/SILVER/DAMAGES/
  ENDORSE_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/SILVER/ENDORSE/
  PRIMARY_PERSON_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/SILVER/PRIMARY_PERSON/
  RESTRICT_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/SILVER/RESTRICT/
  UNITS_USE_PATH: C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/SILVER/UNITS/
GOLD_PATH:
  C:/Users/sanch/PROJECTS/CAR-CRASH-SDE/DATA/GOLD/
COLUMNS:
  PRIMARY_PERSON_COLUMNS:
    - CRASH_ID
    - PRSN_ETHNICITY_ID
    - PRSN_GNDR_ID
    - PRSN_AIRBAG_ID
    - PRSN_ALC_SPEC_TYPE_ID
    - PRSN_ALC_RSLT_ID
    - PRSN_BAC_TEST_RSLT
    - DRVR_LIC_TYPE_ID
    - DRVR_LIC_STATE_ID
    - PRSN_INJRY_SEV_ID
    - DRVR_ZIP
    - DEATH_CNT
    - PRSN_TYPE_ID
  CHARGES_COLUMNS:
    - "*"
  DAMAGES_COLUMNS:
    - "*"
  ENDORSE_COLUMNS:
    - "*"
  RESTRICT_COLUMNS:
    - "*"
  UNITS_COLUMNS:
    - CRASH_ID
    - VEH_BODY_STYL_ID
    - VIN
    - VEH_MAKE_ID
    - VEH_HNR_FL
    - TOT_INJRY_CNT
    - DEATH_CNT
    - CONTRIB_FACTR_1_ID
    - CONTRIB_FACTR_2_ID
    - CONTRIB_FACTR_P1_ID
    - VEH_DMAG_SCL_1_ID
    - VEH_DMAG_SCL_2_ID
    - FIN_RESP_TYPE_ID
    - VEH_COLOR_ID